# Generated by Django 6.0.7 on 2026-08-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, help_text='Оставьте поле пустым, если матч не сыгран или ничья', max_length=100, null=True),
        ),
    ]
